# Use Node.js as the base image
FROM node:20.12.0-bookworm-slim

# Set the working directory inside the container
WORKDIR /usr/src/app

# Copy package.json
COPY svelte-project/package.json ./

# Install dependencies
RUN npm install

# Copy the rest of the application
COPY svelte-project/. .

# Build the Svelte application
RUN npm run build

# Expose the port the app runs on
EXPOSE 80

# Command to run the application
CMD ["npm", "run", "preview", "--", "--host", "0.0.0.0"]